import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Image from "next/image";
import logo from "@/public/logo/black/warrior-face.png"

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: LayoutProps<"/">) {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 gap-5">
      <div className="flex size-20 items-center justify-center">
        <Image 
          src={logo} 
          alt={"KOA Warrior Face Logo"} 
          className="drop-shadow-2xl"
        />
      </div>
      {children}
    </div>
  );
}
