import type { Metadata } from "next";
import Image from "next/image";
import logo from "@/public/logo/black/warrior-face.png"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: LayoutProps<"/">) {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 gap-5">
      <div className="flex size-20 items-center justify-center">
        <Image 
          src={logo} 
          alt={"KOA Warrior Face Logo"} 
          className="drop-shadow-2xl"
        />
      </div>
      {children}
    </div>
  );
}
