import Footer from "@/components/shop-front/footer";
import { Header } from "@/components/shop-front/header";
import { Hero } from "@/components/shop-front/hero";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KOA Clothing",
  description: "Generated by create next app",
};

export default function ShopFrontLayout({ children }: LayoutProps<"/">) {
  return (
    <div className="min-h-screen flex flex-col items-center justify-start bg-gray-50"> 
      <Header />
       
      <div className="flex flex-col w-full">
        {children}
      </div> 
      <Footer />  
    </div>
  );
}
