import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: LayoutProps<"/">) {
  return (
    <div className="min-h-screen flex flex-col items-center justify-start bg-gray-50">
      {children}
    </div>
  );
}
