import AdminHeader from "@/components/admin/admin-header";
import { AppSidebar } from "@/components/admin/sidebar/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { auth } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "KOA Admin Dashboard",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }: LayoutProps<"/">) {
  const { sessionClaims } = await auth.protect()
  
  const role = sessionClaims?.metadata?.role;

  if (role !== 'admin') {
    redirect('/') 
  }

  return (
    <SidebarProvider>
      <div className="min-h-screen flex w-full bg-gray-50">
        <AppSidebar />
        <main className="flex-1 flex flex-col min-w-0">
          <AdminHeader />
          <div className="flex-1 p-6">
            {children}
          </div>
        </main>
      </div>
    </SidebarProvider>
  );
}
